[[redirects]]
from = "/*"
to = "/index.html"

status = 200

[build]
	command = "npm run build"
	functions = "netlify/functions"
    edge_functions="netlify/edge-functions"
	publish = "dist"

[functions]
        node_bundler = "esbuild"

